# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

# Kotlin
kotlin.code.style=official

# Compose
android.enableComposeCompilerMetrics=true
